# -*- coding: utf-8 -*-
"""app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179UMaOpPsmyuRiNMWQgpZIIre1OcaVS4
"""

code = """
import streamlit as st

movies = [
  {"name": "Inception", "genre": "sci-fi", "rating": 8.8},
  {"name": "Interstellar", "genre": "sci-fi", "rating": 8.6},
  {"name": "The Matrix", "genre": "sci-fi", "rating": 8.7},
  {"name": "Avatar", "genre": "action", "rating": 7.9},
  {"name": "Titanic", "genre": "romance", "rating": 7.8},
  {"name": "The Notebook", "genre": "romance", "rating": 7.8},
  {"name": "La La Land", "genre": "romance", "rating": 8.0},
  {"name": "3 Idiots", "genre": "comedy", "rating": 8.4},
  {"name": "PK", "genre": "comedy", "rating": 8.1},
  {"name": "Munna Bhai MBBS", "genre": "comedy", "rating": 8.1},
  {"name": "Dangal", "genre": "biography", "rating": 8.3},
  {"name": "MS Dhoni The Untold Story", "genre": "biography", "rating": 7.9},
  {"name": "The Dark Knight", "genre": "action", "rating": 9.0},
  {"name": "The Dark Knight Rises", "genre": "action", "rating": 8.4},
  {"name": "Avengers Endgame", "genre": "action", "rating": 8.4},
  {"name": "Avengers Infinity War", "genre": "action", "rating": 8.4},
  {"name": "Iron Man", "genre": "action", "rating": 7.9},
  {"name": "Spider-Man No Way Home", "genre": "action", "rating": 8.2},
  {"name": "Doctor Strange", "genre": "action", "rating": 7.5},
  {"name": "Black Panther", "genre": "action", "rating": 7.3},
  {"name": "Joker", "genre": "drama", "rating": 8.4},
  {"name": "Fight Club", "genre": "drama", "rating": 8.8},
  {"name": "Forrest Gump", "genre": "drama", "rating": 8.8},
  {"name": "Sholay", "genre": "action", "rating": 8.2},
  {"name": "Kabir Singh", "genre": "romance", "rating": 7.0},
  {"name": "Bajirao Mastani", "genre": "romance", "rating": 7.2},
  {"name": "Padmaavat", "genre": "drama", "rating": 7.0},
  {"name": "Uri The Surgical Strike", "genre": "action", "rating": 8.2},
  {"name": "Kesari", "genre": "action", "rating": 7.4},
  {"name": "Tanhaji", "genre": "action", "rating": 7.6},
  {"name": "Bahubali The Beginning", "genre": "action", "rating": 8.0},
  {"name": "Bahubali 2 The Conclusion", "genre": "action", "rating": 8.2},
  {"name": "RRR", "genre": "action", "rating": 7.8},
  {"name": "KGF Chapter 1", "genre": "action", "rating": 8.2},
  {"name": "KGF Chapter 2", "genre": "action", "rating": 8.3},
  {"name": "Pushpa The Rise", "genre": "action", "rating": 7.6},
  {"name": "Drishyam", "genre": "thriller", "rating": 8.2},
  {"name": "Drishyam 2", "genre": "thriller", "rating": 8.4},
  {"name": "Andhadhun", "genre": "thriller", "rating": 8.2},
  {"name": "Kahaani", "genre": "thriller", "rating": 8.1},
  {"name": "Zindagi Na Milegi Dobara", "genre": "drama", "rating": 8.2},
  {"name": "Dil Chahta Hai", "genre": "comedy", "rating": 8.1},
  {"name": "Wake Up Sid", "genre": "drama", "rating": 7.6},
  {"name": "Barfi", "genre": "romance", "rating": 8.1},
  {"name": "Queen", "genre": "drama", "rating": 8.2},
  {"name": "Chhichhore", "genre": "comedy", "rating": 8.3},
  {"name": "Stree", "genre": "horror", "rating": 7.5},
  {"name": "Bhool Bhulaiyaa", "genre": "horror", "rating": 7.5},
  {"name": "Conjuring", "genre": "horror", "rating": 7.5},
  {"name": "It", "genre": "horror", "rating": 7.3}
]

def get_movies_by_genre(genre):
    return [m["name"] for m in movies if m["genre"].lower() == genre.lower()]

def get_movie_rating(movie):
    for m in movies:
        if m["name"].lower() == movie.lower():
            return m["rating"]
    return None

def get_top_movies():
    return sorted(movies, key=lambda x: x["rating"], reverse=True)[:5]

st.set_page_config(page_title="Movie Chatbot", page_icon="🎬", layout="centered")
st.title("🎬 Movie Chatbot (ChatGPT Style)")

if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "Hi! I am your Movie Bot 🎥 Ask me for recommendations, ratings, or top movies."}
    ]

# Display chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# User input
user_input = st.chat_input("Ask something like: suggest action movies, rating Inception, top movies")

if user_input:
    st.session_state.messages.append({"role": "user", "content": user_input})

    msg = user_input.lower()
    response = ""

    if "hello" in msg or "hi" in msg:
        response = "Hello! How can I help you with movies? 🎬"

    elif "suggest" in msg or "recommend" in msg:
        words = msg.split()
        genre = words[-1]
        result = get_movies_by_genre(genre)
        if result:
            response = "Here are some movies:\n" + ", ".join(result[:10])
        else:
            response = "No movies found for this genre."

    elif "rating" in msg:
        movie = msg.replace("rating", "").strip()
        rating = get_movie_rating(movie)
        if rating:
            response = f"⭐ Rating of {movie.title()} is {rating}"
        else:
            response = "Movie not found 😅"

    elif "top" in msg:
        top = get_top_movies()
        response = "🔥 Top 5 Movies:\n" + "\n".join([f"{m['name']} ({m['rating']})" for m in top])

    elif "how are you" in msg:
        response = "I'm doing great! Ready to recommend movies 🍿"

    else:
        response = "Try asking: suggest action, rating Inception, top movies"

    st.session_state.messages.append({"role": "assistant", "content": response})

    with st.chat_message("assistant"):
        st.markdown(response)

"""

with open("app.py", "w", encoding="utf-8") as f:
    f.write(code)

print("app.py created")

with open("requirements.txt", "w") as f:
    f.write("streamlit")

print("requirements.txt created")

import os
print(os.listdir())

