# -*- coding: utf-8 -*-
"""app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179UMaOpPsmyuRiNMWQgpZIIre1OcaVS4
"""

with open("app.py", "w", encoding="utf-8") as f:
    f.write(code)

print("app.py created")

with open("requirements.txt", "w") as f:
    f.write("streamlit")

print("requirements.txt created")

import os
print(os.listdir())

